### ISSUE TITLE
[SOLVED] pdf viewer crashes on api level 30

### ISSUE THREAD

**Issue by bipin-adhikari-webo** [liyuanhust/flutter_simple_pdf_viewer#7]
Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30

**Comment by bipin-adhikari-webo** [comment]
java.lang.ExceptionInInitializerError
E/AndroidRuntime( 7294): 	at okhttp3.internal.platform.Platform.get(Platform.java:85)
E/AndroidRuntime( 7294): 	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
E/AndroidRuntime( 7294): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262)
E/AndroidRuntime( 7294): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1054)
E/AndroidRuntime( 7294): 	at com.liyuanhust.pdfviewer.FileLoader.<clinit>(FileLoader.kt:155)
E/AndroidRuntime( 7294): 	at com.liyuanhust.pdfviewer.PdfView.<init>(PdfView.kt:30)
E/AndroidRuntime( 7294): 	at com.liyuanhust.pdfviewer.PdfViewerFactory.create(PdfViewerFactory.kt:14)
E/AndroidRuntime( 7294): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/AndroidRuntime( 7294): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/AndroidRuntime( 7294): 	at android.app.Dialog.show(Dialog.java:313)
E/AndroidRuntime( 7294): 	at android.app.Presentation.show(Presentation.java:257)
E/AndroidRuntime( 7294): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/AndroidRuntime( 7294): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/AndroidRuntime( 7294): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/AndroidRuntime( 7294): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/AndroidRuntime( 7294): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime( 7294): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 7294): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 7294): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/AndroidRuntime( 7294): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 7294): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime( 7294): 	at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime( 7294): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 7294): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7294): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 7294): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 7294): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
E/AndroidRuntime( 7294): 	at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
E/AndroidRuntime( 7294): 	at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
E/AndroidRuntime( 7294): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
E/AndroidRuntime( 7294): 	... 26 more

**Comment by bipin-adhikari-webo** [comment]
Fixed it. If anyone wants the fix, change the okhttp dependency version to 3.14.7 in the simple_pdf_viewer library present in /flutter/.pub-cache/hosted/pub.dartlang.org/  , it is working fine in android 11 as well.
